name: Release Update
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get package version
        id: version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Release for version ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
